replicaCount: 1

image:
  pullPolicy: Always
  tag: v0.1.1
  # Overrides the image tag whose default is the chart appVersion.

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

autoscaling:
 enabled: false

serviceAccount: 
 create: false

ingress:
 enabled: false