spring.application.name: carbonataplate
server.port: 8181
spring:
  security:
    oauth2:
      client:
        registration:
          carbonata-plate-client:
            provider: camunda-platform-auth
            client-id: carbonataplate
            client-secret: Gz8T3yg0ELt8GlwOGBP9zZx7W6k7WEeJ
        provider:
          camunda-platform-auth:
            issuer-uri: Gz8T3yg0ELt8GlwOGBP9zZx7W6k7WEeJ
carbonata-plate:
  camunda-optimize:
    base-path: http://localhost:8083