apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fibonacci-worker.fullname" . }}
  labels:
    app: fibonacci-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       app: fibonacci-worker
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
      labels:
        app: fibonacci-worker
    spec:
      containers:
        - name: fibonacci-worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLIENT_REGION
              value: {{ quote .Values.container.env.saasRegion }}
            - name: CLUSTER_ID
              value: {{ quote .Values.container.env.saasClusterId }}
            - name: CLIENT_ID
              value: {{ quote .Values.container.env.saasClientId }}
            - name: CLIENT_SECRET
              value: {{ quote .Values.container.env.saasClientSecret }}
            - name: CLIENT_MODE
              value: {{ quote .Values.container.env.saasClientMode }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP