apiVersion: v1
kind: Service
metadata:
  name: {{ include "fibonacci-worker.fullname" . }}
  labels:
    app: fibonacci-worker
    job: {{ .Values.service.jobName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: fibonacci-worker