apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fibonacci-worker
  labels:
    release: "kube-prometheus-stack"
    app: "kube-prometheus-stack"
  namespace: worker
spec:
  jobLabel: job
  endpoints:
    - interval: 5s
      path: /actuator/prometheus
      port: http
  selector:
    matchLabels:
      app: fibonacci-worker