spring:
  application:
    name: fibonacci-worker

camunda:
  client:
    auth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
    cluster-id: ${CLUSTER_ID}
    region: ${CLIENT_REGION}
    mode: ${CLIENT_MODE}

#camunda:
#  client:
#    zeebe:
#      base-url: http://127.0.0.1:26500

server:
  port: ${SERVER_PORT:8080}

# enable prometheus
management:
 endpoints:
  web:
   exposure:
    include: prometheus
 metrics:
  export:
   prometheus:
    enabled: true

