replicaCount: 1
kubernetesClusterDomain: cluster.local

container:
  env:
   saasRegion: null
   saasClusterId: null
   saasClientId: null
   saasClientSecret: null
   saasClientMode: null

image:
  repository: jabowski/fibonacci-worker
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.1.1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

autoscaling:
 enabled: false

serviceAccount: 
 create: false

ingress:
 enabled: false