name: Backend - Continuous Integration - CarboNataplate

on:
  push:
    branches: [ main ]
    paths:
      - 'src/carbonataplate/**'
  pull_request:
    branches: "**"
    paths:
      - 'src/carbonataplate/**'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build Carbonataplate
        working-directory: ./src/carbonataplate
        run: ./gradlew clean check
